import './style.css'

export { default as DynamicTable } from './dynamic-table'
export * from './interfaces'
export * from './utils/use-table'
export * from './defines/define-columns'
export * from './defines/define-forms'
export * from './defines/define-table-load'
export * from './defines/define-table-render'
export { default } from './install'
